### ISSUE TITLE
The file won't start.

### ISSUE THREAD

**Issue by Vansed111** [Alb-310/Geogramint#24]
I try to run the file "geogramint", the console appears for 1 second and immediately disappears. What's the problem?

**Comment by masaguaro** [comment]
The same happens to me but with this additional error message:

**from kivy_garden.mapview import MapMarker
 ImportError: cannot import name 'MapMarker' from 'kivy_garden.mapview' (unknown location)**

**Comment by Alb-310** [comment]
> I try to run the file "geogramint", the console appears for 1 second and immediately disappears. What's the problem? 

Hello, I will need some logs to be able to help you. Try running the tool from a console and send the error logs

**Comment by Alb-310** [comment]
> The same happens to me but with this additional error message:
> 
> 
> 
> **from kivy_garden.mapview import MapMarker
> 
>  ImportError: cannot import name 'MapMarker' from 'kivy_garden.mapview' (unknown location)**

Hello, on which OS are you and which python version? And did you install all dependencies correctly?

**Comment by lMikoFoxl** [comment]
> > The same happens to me but with this additional error message:
> > **from kivy_garden.mapview import MapMarker
> > ImportError: cannot import name 'MapMarker' from 'kivy_garden.mapview' (unknown location)**
> 
> Hello, on which OS are you and which python version? And did you install all dependencies correctly?

Bro, problem with lib "cryptography", OS windows 10, version py 3.9(on py 3.8 several libs don't want to install)
` 
Traceback (most recent call last):
   File "Geogramint-master\geogramint.py", line 12, in <module>
     from api import TelegramAPIRequests
   File "Geogramint-master\api\TelegramAPIRequests.py", line 9, in <module>
     from utils import ressources
   File "UsersGeogramint-master\utils\ressources.py", line 15, in <module>
     from xhtml2pdf import pisa, default
   File "AppData\Local\Programs\Python\Python39\lib\site-packages\xhtml2pdf\pisa.py", line 26, in <module>
     from xhtml2pdf.document import pisaDocument
   File "AppData\Local\Programs\Python\Python39\lib\site-packages\xhtml2pdf\document.py", line 24, in <module>
     from xhtml2pdf.builders.signs import PDFSignature
   File "AppData\Local\Programs\Python\Python39\lib\site-packages\xhtml2pdf\builders\signs.py", line 5, in <module>
     from pyhanko.pdf_utils.incremental_writer import IncrementalPdfFileWriter
   File "AppData\Local\Programs\Python\Python39\lib\site-packages\pyhanko\pdf_utils\incremental_writer.py", line 8, in <module>
     from . import generic, misc
   File "AppData\Local\Programs\Python\Python39\lib\site-packages\pyhanko\pdf_utils\generic.py", line 22, in <module>
     from .misc import (
   File "AppData\Local\Programs\Python\Python39\lib\site-packages\pyhanko\pdf_utils\misc.py", line 17, in <module>
     from pyhanko_certvalidator.util import CancelableAsyncIterator, ConsList
   File "AppData\Local\Programs\Python\Python39\lib\site-packages\pyhanko_certvalidator\__init__.py", line 8, in <module>
     from .context import ValidationContext
   File "AppData\Local\Programs\Python\Python39\lib\site-packages\pyhanko_certvalidator\context.py", line 13, in <module>
     from .fetchers.requests_fetchers import RequestsFetcherBackend
   File "AppData\Local\Programs\Python\Python39\lib\site-packages\pyhanko_certvalidator\fetchers\requests_fetchers\__init__.py", line 8, in <module>
     from .cert_fetch_client import RequestsCertificateFetcher
   File "AppData\Local\Programs\Python\Python39\lib\site-packages\pyhanko_certvalidator\fetchers\requests_fetchers\cert_fetch_client.py", line 7, in <module>
     from ...errors import CertificateFetchError
   File "AppData\Local\Programs\Python\Python39\lib\site-packages\pyhanko_certvalidator\errors.py", line 6, in <module>
     from cryptography.exceptions import InvalidSignature
   File "AppData\Local\Programs\Python\Python39\lib\site-packages\cryptography\exceptions.py", line 9, in <module>
     from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
 ImportError: DLL load failed while importing _rust: The specified procedure could not be found.
`

**Comment by R3D-W** [comment]
Good evening, I don't know what to try anymore, I installed the program launched and I can't start it, this is the error that appears. I think they are related to libraries, can anyone help me? Win10 Usage

Traceback (most recent call last):
File "geogramint.py", line 400, in
trio.run(Geogramint().run())
File "kivy\app.py", line 956, in run
File "kivy\base.py", line 574, in runTouchApp
File "kivy\base.py", line 339, in mainloop
File "kivy\base.py", line 391, in idle
File "kivy\clock.py", line 783, in tick_draw
File "kivy_clock.pyx", line 662, in kivy._clock.CyClockBase._process_events_before_frame
File "kivy_clock.pyx", line 708, in kivy._clock.CyClockBase._process_events_before_frame
File "kivy_clock.pyx", line 704, in kivy._clock.CyClockBase._process_events_before_frame
File "kivy_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
File "kivy_garden\mapview\view.py", line 768, in do_update
File "kivy_garden\mapview\view.py", line 880, in load_visible_tiles
File "kivy_garden\mapview\view.py", line 893, in load_tile
File "kivy_garden\mapview\view.py", line 907, in load_tile_for_source
File "kivy_garden\mapview\source.py", line 212, in fill_tile
File "kivy_garden\mapview\downloader.py", line 37, in instance
File "kivy_garden\mapview\downloader.py", line 52, in init
File "os.py", line 223, in makedirs
PermissionError: [WinError 5] Accesso negato: 'cache

**Comment by k1bb5** [comment]
Well there is no access via the Telegram IG and # but I don't know how to help
