### ISSUE TITLE
EXE after installation don't open

### ISSUE THREAD

**Issue by R3D-W** [Alb-310/Geogramint#31]
Good evening, I don't know what to try anymore, I installed the program launched and I can't start it, this is the error that appears. I think they are related to libraries, can anyone help me? Win10 Usage

Traceback (most recent call last):
  File "geogramint.py", line 400, in <module>
    trio.run(Geogramint().run())
  File "kivy\app.py", line 956, in run
  File "kivy\base.py", line 574, in runTouchApp
  File "kivy\base.py", line 339, in mainloop
  File "kivy\base.py", line 391, in idle
  File "kivy\clock.py", line 783, in tick_draw
  File "kivy\_clock.pyx", line 662, in kivy._clock.CyClockBase._process_events_before_frame
  File "kivy\_clock.pyx", line 708, in kivy._clock.CyClockBase._process_events_before_frame
  File "kivy\_clock.pyx", line 704, in kivy._clock.CyClockBase._process_events_before_frame
  File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
  File "kivy_garden\mapview\view.py", line 768, in do_update
  File "kivy_garden\mapview\view.py", line 880, in load_visible_tiles
  File "kivy_garden\mapview\view.py", line 893, in load_tile
  File "kivy_garden\mapview\view.py", line 907, in load_tile_for_source
  File "kivy_garden\mapview\source.py", line 212, in fill_tile
  File "kivy_garden\mapview\downloader.py", line 37, in instance
  File "kivy_garden\mapview\downloader.py", line 52, in __init__
  File "os.py", line 223, in makedirs
PermissionError: [WinError 5] Accesso negato: 'cache

**Comment by Alb-310** [comment]
Hello, sorry for the late reply, it seems that you have permission errors. Try installing Geogramint in a place where it doesn't need Administrator permissions like for example in folder on your desktop
