### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by NVA-1986** [Alb-310/Geogramint#6]
Traceback (most recent call last):
  File "geogramint.py", line 244, in <module>
    trio.run(Geogramint().run())
  File "kivy\app.py", line 955, in run
  File "kivy\base.py", line 574, in runTouchApp
  File "kivy\base.py", line 339, in mainloop
  File "kivy\base.py", line 391, in idle
  File "kivy\clock.py", line 783, in tick_draw
  File "kivy\_clock.pyx", line 662, in kivy._clock.CyClockBase._process_events_before_frame
  File "kivy\_clock.pyx", line 708, in kivy._clock.CyClockBase._process_events_before_frame
  File "kivy\_clock.pyx", line 704, in kivy._clock.CyClockBase._process_events_before_frame
  File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
  File "kivy_garden\mapview\view.py", line 768, in do_update
  File "kivy_garden\mapview\view.py", line 880, in load_visible_tiles
  File "kivy_garden\mapview\view.py", line 893, in load_tile
  File "kivy_garden\mapview\view.py", line 907, in load_tile_for_source
  File "kivy_garden\mapview\source.py", line 212, in fill_tile
  File "kivy_garden\mapview\downloader.py", line 37, in instance
  File "kivy_garden\mapview\downloader.py", line 52, in __init__
  File "os.py", line 223, in makedirs
PermissionError: [WinError 5] Accès refusé: 'cache'

**Comment by Alb-310** [comment]
Hello @NVA-1986

You need to provide more context in your issue

**Comment by NVA-1986** [comment]
@Alb-310 Following the installation of the executable on my Windows 11 machine, when I launch the software it gives me this error.

**Comment by Alb-310** [comment]
@NVA-1986 It looks like Geogramint doesn't have enough permissions where it is installed, try running it as administrator.

If that doesn't work, uninstall it and try installing the tool on your desktop to see if that solves the problem.

**Comment by NVA-1986** [comment]
I installed it on another machine and it's good.
On the other hand, when I noted the API key in the software, my telegram account was banned and I no longer have access.

**Comment by Alb-310** [comment]
It's weird, I and many others have used the tool many times and our accounts got no problems 🤔
